
package gui;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import entity.LoaiSanpham;
import entity.Nhacungcap;
import entity.Sanpham;
import service.SanphamService;

/**
 *
 * @author Lenovo
 */
public class ProductFrame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form ProductFrame
	 */
	private SecurityManager securityManager;
	private SanphamService sanphamDao;
	int chucnang = 0;
	String path = "";
	byte[] hinhanh = null;

	public ProductFrame() {
		initComponents();
		this.securityManager = System.getSecurityManager();
		if (this.securityManager == null) {
			System.setProperty("java.security.policy", "policy/policy.policy");
			System.setSecurityManager(new SecurityManager());
		}
		try {
			sanphamDao = (SanphamService) Naming.lookup("rmi://192.168.1.6:1099/sanphamService");
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		this.setLocationRelativeTo(null);
		disabled();
		showSanpham();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelQuanLySP = new javax.swing.JPanel();
        labelQLSP = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnThoat = new javax.swing.JButton();
        labelHinhAnh = new javax.swing.JLabel();
        labelMaSP = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        labelTenSP = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        labelDonGia = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        labelSoLuongTon = new javax.swing.JLabel();
        txtSoLuongTon = new javax.swing.JTextField();
        labelTrangThai = new javax.swing.JLabel();
        txtTrangThai = new javax.swing.JTextField();
        labelMaNCC = new javax.swing.JLabel();
        labelTenTG = new javax.swing.JLabel();
        txtTenTG = new javax.swing.JTextField();
        labelSoTrang = new javax.swing.JLabel();
        txtSoTrang = new javax.swing.JTextField();
        labelNXB = new javax.swing.JLabel();
        txtNXB = new javax.swing.JTextField();
        cbMaNCC = new javax.swing.JComboBox<>();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnIn = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtTenSPTimKiem = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        labelTenSPTimKiem = new javax.swing.JLabel();
        labelLoaiSP = new javax.swing.JLabel();
        cbLoaiSP = new javax.swing.JComboBox<>();
        btnChonanh = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableQuanLySP = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelQuanLySP.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        labelQLSP.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelQLSP.setText("QUẢN LÝ SÁCH");

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/out.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        labelHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHinhAnh.setText("Ảnh");
        labelHinhAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelMaSP.setText("Mã sản phẩm");

        labelTenSP.setText("Tên sản phẩm");

        labelDonGia.setText("Đơn giá");

        labelSoLuongTon.setText("Sô lượng tồn");

        labelTrangThai.setText("Trạng thái");

        labelMaNCC.setText("Nhà cung cấp");

        labelTenTG.setText("Tên tác giả");

        labelSoTrang.setText("Số trang");

        labelNXB.setText("Nhà xuất bản");

        cbMaNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fix.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        btnLuu.setText("Lưiu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer.png"))); // NOI18N
        btnIn.setText("  In");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset.png"))); // NOI18N
        btnReset.setText("Quay lại");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnTim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        labelTenSPTimKiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTenSPTimKiem.setText("Tên Sản Phẩm");

        labelLoaiSP.setText("Loại sản phẩm");

        cbLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sách" }));

        btnChonanh.setText("Chọn ảnh");
        btnChonanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonanhActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelQuanLySPLayout = new javax.swing.GroupLayout(panelQuanLySP);
        panelQuanLySP.setLayout(panelQuanLySPLayout);
        panelQuanLySPLayout.setHorizontalGroup(
            panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelQuanLySPLayout.createSequentialGroup()
                .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelQuanLySPLayout.createSequentialGroup()
                        .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelQuanLySPLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelQuanLySPLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelQuanLySPLayout.createSequentialGroup()
                                    .addComponent(labelLoaiSP)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelQuanLySPLayout.createSequentialGroup()
                                    .addComponent(labelDonGia)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelQuanLySPLayout.createSequentialGroup()
                                    .addComponent(labelMaNCC)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelQuanLySPLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(panelQuanLySPLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnChonanh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelNXB)
                        .addGap(18, 18, 18)
                        .addComponent(txtNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelQuanLySPLayout.createSequentialGroup()
                        .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelQuanLySPLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelQuanLySPLayout.createSequentialGroup()
                                        .addComponent(labelMaSP)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelQuanLySPLayout.createSequentialGroup()
                                        .addComponent(labelTenTG)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTenTG, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelQuanLySPLayout.createSequentialGroup()
                                        .addComponent(labelSoLuongTon)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelQuanLySPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)))
                        .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelQuanLySPLayout.createSequentialGroup()
                                .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuanLySPLayout.createSequentialGroup()
                                        .addComponent(labelTenSP)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuanLySPLayout.createSequentialGroup()
                                        .addComponent(labelTrangThai)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuanLySPLayout.createSequentialGroup()
                                        .addComponent(labelSoTrang)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSoTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuanLySPLayout.createSequentialGroup()
                                .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelQuanLySPLayout.createSequentialGroup()
                                        .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(labelTenSPTimKiem)
                                        .addGap(0, 34, Short.MAX_VALUE))
                                    .addGroup(panelQuanLySPLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuanLySPLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTenSPTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
            .addGroup(panelQuanLySPLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnThoat)
                .addGap(321, 321, 321)
                .addComponent(labelQLSP)
                .addContainerGap(505, Short.MAX_VALUE))
        );
        panelQuanLySPLayout.setVerticalGroup(
            panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuanLySPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThoat)
                    .addComponent(labelQLSP))
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelQuanLySPLayout.createSequentialGroup()
                        .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(labelMaSP)
                            .addComponent(txtMaSP)
                            .addComponent(labelTenSP)
                            .addComponent(txtTenSP)
                            .addComponent(labelLoaiSP)
                            .addComponent(cbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDonGia)
                            .addComponent(txtDonGia)
                            .addComponent(labelSoLuongTon)
                            .addComponent(txtSoLuongTon)
                            .addComponent(labelTrangThai)
                            .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelTenTG)
                                .addComponent(txtTenTG)
                                .addComponent(labelSoTrang)
                                .addComponent(txtSoTrang))
                            .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelMaNCC)
                                .addComponent(cbMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelQuanLySPLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelNXB)
                                    .addComponent(txtNXB))
                                .addGap(18, 18, 18)
                                .addComponent(btnTim))
                            .addGroup(panelQuanLySPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelTenSPTimKiem)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenSPTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addGroup(panelQuanLySPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSua)
                            .addComponent(btnLuu)
                            .addComponent(btnIn)
                            .addComponent(btnReset)
                            .addComponent(btnXoa)
                            .addComponent(btnThem)))
                    .addGroup(panelQuanLySPLayout.createSequentialGroup()
                        .addComponent(labelHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnChonanh)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tableQuanLySP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Loại sản phẩm", "Mã sản phẩm", "Tên sản phẩm", "Đơn giá", "Số lượng tồn", "Trạng thái", "Mã nhà sản xuất", "Tên tác giả", "Số trang", "Nhà xuất bản"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableQuanLySP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableQuanLySPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableQuanLySP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(panelQuanLySP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelQuanLySP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void tableQuanLySPMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tableQuanLySPMouseClicked
		// TODO add your handling code here:

		mouseClickTable();
	}// GEN-LAST:event_tableQuanLySPMouseClicked

	private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXoaActionPerformed
		// TODO add your handling code here:
		try {
			deleteSanpham(Integer.parseInt(txtMaSP.getText()));
		} catch (NumberFormatException | RemoteException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}// GEN-LAST:event_btnXoaActionPerformed

	private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThoatActionPerformed
		dispose();
		new HomeFrame().setVisible(true);
	}// GEN-LAST:event_btnThoatActionPerformed

	private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSuaActionPerformed
		enabled();
		btnLuu.setEnabled(true);
		btnThem.setEnabled(false);
		btnXoa.setEnabled(false);
		chucnang = 2;

	}// GEN-LAST:event_btnSuaActionPerformed

	private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLuuActionPerformed
		if (chucnang == 1) {
			try {
				insertSanpham();
			} catch (RemoteException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		} else if (chucnang == 2) {
			try {
				updateSanpham();
			} catch (RemoteException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		path = "";
		hinhanh = null;
		refesh();
	}// GEN-LAST:event_btnLuuActionPerformed

	private void btnInActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnInActionPerformed

	}// GEN-LAST:event_btnInActionPerformed

	private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnResetActionPerformed
		disabled();
		refesh();
	}// GEN-LAST:event_btnResetActionPerformed

	private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTimActionPerformed
		String tukhoa = txtTenSPTimKiem.getText();
		try {
			List<Sanpham> dsSanpham = sanphamDao.getSanphamByName(tukhoa);
			if(dsSanpham.size() == 0) {
				JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm!");
			}
			DefaultTableModel model = new DefaultTableModel(
					new Object[] { "Loại sản phẩm", "Mã sản phẩm", "Tên sản phẩm", "Đơn giá", "Số lượng tồn",
							"Trạng thái", "Nhà sản xuất", "Tên tác giả", "Số trang", "Nhà xuất bản" },
					0);
			for (Sanpham sp : dsSanpham) {
				Object[] obj = { sp.getLoaisanpham().getTenloaisp(), sp.getId(), sp.getTenSanpham(), sp.getDongia(),
						sp.getSoluongton(), sp.getTrangthai(), sp.getNhacungcap().getTenNhaCC(), sp.getTenTacgia(),
						sp.getSotrang(), sp.getNhaxuatban() };
				model.addRow(obj);
			}
			tableQuanLySP.setModel(model);
		} catch (RemoteException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}// GEN-LAST:event_btnTimActionPerformed

	private void btnChonanhActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnChonanhActionPerformed
		JFileChooser chooser = new JFileChooser();
		chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
		chooser.setDialogTitle("Chọn ảnh");

		FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Image", "jpg", "png");
		chooser.addChoosableFileFilter(filter);

		int result = chooser.showSaveDialog(null);
		File file = chooser.getSelectedFile();
		String filename = file.getName();
		if (filename.endsWith(".jpg") || filename.endsWith(".JPG") || filename.endsWith(".png")
				|| filename.endsWith(".PNG")) {
			if (result == JFileChooser.APPROVE_OPTION) {
				path = file.getAbsolutePath();
				ImageIcon imgIcon = new ImageIcon(path);
				Image img = imgIcon.getImage();

				Image newImg = img.getScaledInstance(labelHinhAnh.getWidth(), labelHinhAnh.getHeight(),
						Image.SCALE_SMOOTH);

				ImageIcon icon = new ImageIcon(newImg);
				labelHinhAnh.setIcon(icon);
				hinhanh = null;
			}
		} else
			JOptionPane.showMessageDialog(this, "Chọn sai tệp, vui lòng chọn tệp hình ảnh");
	}// GEN-LAST:event_btnChonanhActionPerformed

	private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThemActionPerformed
		refesh();
		enabled();
		btnLuu.setEnabled(true);
		txtMaSP.setEnabled(false);
		labelHinhAnh.setIcon(null);
		btnSua.setEnabled(false);
		btnXoa.setEnabled(false);
		chucnang = 1;
	}// GEN-LAST:event_btnThemActionPerformed

	/**
	 * Xoa san pham
	 * @param id
	 * @throws RemoteException
	 */
	private void deleteSanpham(int id) throws RemoteException {
		int yes = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa sản phẩm này?", "Cảnh báo",
				JOptionPane.YES_NO_CANCEL_OPTION);
		if (yes == JOptionPane.YES_OPTION) {
			if (sanphamDao.deleteSanpham(id)) {
				JOptionPane.showMessageDialog(this, "Sản phẩm được xóa thành công!");
			} else {
				JOptionPane.showMessageDialog(this, "Sản phẩm xóa không thành công!\nVui lòng kiểm tra lại");
			}
		}
		refesh();
		disabled();
	}

	/**
	 * Sua san pham
	 * 
	 * @throws RemoteException
	 */
	private void updateSanpham() throws RemoteException {
		Sanpham sanpham = new Sanpham();
		String tenNhaCC = cbMaNCC.getSelectedItem().toString();
		sanpham.setLoaisanpham(new LoaiSanpham("SA", "Sách"));
		List<Nhacungcap> nhacungcaps = sanphamDao.getNhacungcapServices();
		for (Nhacungcap nhacc : nhacungcaps) {
			if (nhacc.getTenNhaCC().equals(tenNhaCC)) {
				sanpham.setNhacungcap(new Nhacungcap(nhacc.getId(), nhacc.getTenNhaCC(), nhacc.getDiachi()));
			}
		}
		if (txtSoTrang.getText().equals("")) {
			sanpham.setSotrang(0);
		} else {
			sanpham.setSotrang(Integer.parseInt(txtSoTrang.getText()));
		}
		sanpham.setId(Integer.parseInt(txtMaSP.getText().trim()));
		sanpham.setTenSanpham(txtTenSP.getText().trim());
		sanpham.setDongia(Double.parseDouble(txtDonGia.getText().trim()));
		sanpham.setSoluongton(Integer.parseInt(txtSoLuongTon.getText().trim()));
		sanpham.setTrangthai(txtTrangThai.getText());
		sanpham.setTenTacgia(txtTenTG.getText().trim());
		sanpham.setNhaxuatban(txtNXB.getText());
		if (hinhanh != null) {
			sanpham.setHinhanh(hinhanh);
		} else {
			File file = new File(path);
			byte[] hinhanh = new byte[(int) file.length()];
			try {
				FileInputStream fileInputStream = new FileInputStream(file);
				fileInputStream.read(hinhanh);
				fileInputStream.close();
			} catch (Exception e) {
				// TODO: handle exception
				e.printStackTrace();
			}
			sanpham.setHinhanh(hinhanh);
		}
		if (sanphamDao.updateSanpham(sanpham)) {
			JOptionPane.showMessageDialog(this, "Sản phẩm đã được cập nhật thành công!");
		} else {
			JOptionPane.showMessageDialog(this, "Sản phẩm không cập nhật thành công!\nVui lòng kiểm tra lại");
		}
	}

	/**
	 * Table Mouse Click
	 * 
	 * @throws RemoteException
	 */
	private void mouseClickTable() {
		int click = tableQuanLySP.getSelectedRow();
		TableModel tableModel = tableQuanLySP.getModel();
		cbLoaiSP.setSelectedItem(tableModel.getValueAt(click, 0).toString());
		txtMaSP.setText(tableModel.getValueAt(click, 1).toString());
		txtTenSP.setText(tableQuanLySP.getValueAt(click, 2).toString());
		txtDonGia.setText(tableModel.getValueAt(click, 3).toString());
		txtSoLuongTon.setText(tableModel.getValueAt(click, 4).toString());
		if (Integer.parseInt(tableModel.getValueAt(click, 4).toString()) > 0) {
			txtTrangThai.setText("Còn hàng");
		} else
			txtTrangThai.setText("Hết hàng");
		cbMaNCC.setSelectedItem(tableModel.getValueAt(click, 6).toString());
		txtTenTG.setText(tableModel.getValueAt(click, 7).toString());
		txtSoTrang.setText(tableModel.getValueAt(click, 8).toString());
		txtNXB.setText(tableModel.getValueAt(click, 9).toString());
		btnSua.setEnabled(true);
		btnXoa.setEnabled(true);

		try {
			Sanpham sanpham = sanphamDao.getSanphamById(Integer.parseInt(tableModel.getValueAt(click, 1).toString()));
			hinhanh = sanpham.getHinhanh();
			ImageIcon icon = new ImageIcon(hinhanh);
			Image img = icon.getImage();
			Image newImg = img.getScaledInstance(labelHinhAnh.getWidth(), labelHinhAnh.getHeight(), Image.SCALE_SMOOTH);
			ImageIcon imgIcon = new ImageIcon(newImg);
			labelHinhAnh.setIcon(imgIcon);
		} catch (NumberFormatException | RemoteException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * Them san pham
	 * 
	 * @throws RemoteException
	 */
	private void insertSanpham() throws RemoteException {
		String tenLoaiSP = cbLoaiSP.getSelectedItem().toString();
		String tenNhaCC = cbMaNCC.getSelectedItem().toString();
		Sanpham sanpham = new Sanpham();
		sanpham.setLoaisanpham(new LoaiSanpham("SA", tenLoaiSP));
		if (txtSoTrang.getText().equals("")) {
			sanpham.setSotrang(0);
		} else {
			sanpham.setSotrang(Integer.parseInt(txtSoTrang.getText()));
		}

		List<Nhacungcap> nhacungcaps = sanphamDao.getNhacungcapServices();
		for (Nhacungcap nhacc : nhacungcaps) {
			if (nhacc.getTenNhaCC().equals(tenNhaCC)) {
				sanpham.setNhacungcap(new Nhacungcap(nhacc.getId(), nhacc.getTenNhaCC(), nhacc.getDiachi()));
			}
		}
		if (Integer.parseInt(txtSoLuongTon.getText().trim()) > 0) {
			txtTrangThai.setText("Còn hàng");
		} else {
			txtTrangThai.setText("Hết hàng");
		}
		sanpham.setTenSanpham(txtTenSP.getText().trim());
		sanpham.setDongia(Double.parseDouble(txtDonGia.getText().trim()));
		sanpham.setSoluongton(Integer.parseInt(txtSoLuongTon.getText().trim()));
		sanpham.setTrangthai(txtTrangThai.getText());
		sanpham.setTenTacgia(txtTenTG.getText().trim());
		sanpham.setNhaxuatban(txtNXB.getText());
		File file = new File(path);
		byte[] hinhanh = new byte[(int) file.length()];
		try {
			FileInputStream fileInputStream = new FileInputStream(file);
			fileInputStream.read(hinhanh);
			fileInputStream.close();
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		sanpham.setHinhanh(hinhanh);
		if (sanphamDao.insertSanpham(sanpham)) {
			JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công!!");
			showSanpham();
		} else {
			JOptionPane.showMessageDialog(this, "Thêm không thành công! Vui lòng kiểm tra lại");
		}
	}

	private void refesh() {
		disabled();
		btnThem.setEnabled(true);
		txtDonGia.setText("");
		txtMaSP.setText("");
		txtNXB.setText("");
		txtSoLuongTon.setText("");
		txtSoLuongTon.setText("");
		txtSoTrang.setText("");
		txtTenSP.setText("");
		txtTenSPTimKiem.setText("");
		txtTenTG.setText("");
		txtTrangThai.setText("");
		cbLoaiSP.setSelectedIndex(0);
		cbMaNCC.setSelectedIndex(0);
		labelHinhAnh.setIcon(null);
		showSanpham();
	}

	private void disabled() {
		txtDonGia.setEnabled(false);
		txtMaSP.setEnabled(false);
		txtNXB.setEnabled(false);
		txtSoLuongTon.setEnabled(false);
		txtSoTrang.setEnabled(false);
		txtTenSP.setEnabled(false);
		txtTenTG.setEnabled(false);
		txtTrangThai.setEnabled(false);
		btnIn.setEnabled(false);
		btnLuu.setEnabled(false);
		btnSua.setEnabled(false);
		btnChonanh.setEnabled(false);
		btnXoa.setEnabled(false);
		cbLoaiSP.setEnabled(false);
		cbMaNCC.setEnabled(false);
	}

	private void enabled() {
		txtDonGia.setEnabled(true);
		txtNXB.setEnabled(true);
		txtSoLuongTon.setEnabled(true);
		txtSoTrang.setEnabled(true);
		txtTenSP.setEnabled(true);
		txtTenSPTimKiem.setEnabled(true);
		txtTenTG.setEnabled(true);
		btnChonanh.setEnabled(true);
		cbLoaiSP.setEnabled(true);
		cbMaNCC.setEnabled(true);
	}

	private void showSanpham() {
		try {
			cbMaNCC.removeAllItems();
			List<Sanpham> sanphams = sanphamDao.getSach();
			DefaultTableModel model = new DefaultTableModel(
					new Object[] { "Loại sản phẩm", "Mã sản phẩm", "Tên sản phẩm", "Đơn giá", "Số lượng tồn",
							"Trạng thái", "Nhà sản xuất", "Tên tác giả", "Số trang", "Nhà xuất bản" },
					0);
			for (Sanpham sp : sanphams) {
				Object[] obj = { sp.getLoaisanpham().getTenloaisp(), sp.getId(), sp.getTenSanpham(), sp.getDongia(),
						sp.getSoluongton(), sp.getTrangthai(), sp.getNhacungcap().getTenNhaCC(), sp.getTenTacgia(),
						sp.getSotrang(), sp.getNhaxuatban() };
				model.addRow(obj);
			}

			List<Nhacungcap> dsNhacungcap = sanphamDao.getNhacungcapServices();
			for (Nhacungcap nhacungcap : dsNhacungcap) {
				cbMaNCC.addItem(nhacungcap.getTenNhaCC());
			}
			tableQuanLySP.setModel(model);
		} catch (Exception e) {
			// TODO: handle exception

			e.printStackTrace();
		}
	}

	/**
	 * @param args the command line arguments
	 */

	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ProductFrame().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonanh;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbLoaiSP;
    private javax.swing.JComboBox<String> cbMaNCC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelDonGia;
    private javax.swing.JLabel labelHinhAnh;
    private javax.swing.JLabel labelLoaiSP;
    private javax.swing.JLabel labelMaNCC;
    private javax.swing.JLabel labelMaSP;
    private javax.swing.JLabel labelNXB;
    private javax.swing.JLabel labelQLSP;
    private javax.swing.JLabel labelSoLuongTon;
    private javax.swing.JLabel labelSoTrang;
    private javax.swing.JLabel labelTenSP;
    private javax.swing.JLabel labelTenSPTimKiem;
    private javax.swing.JLabel labelTenTG;
    private javax.swing.JLabel labelTrangThai;
    private javax.swing.JPanel panelQuanLySP;
    private javax.swing.JTable tableQuanLySP;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtNXB;
    private javax.swing.JTextField txtSoLuongTon;
    private javax.swing.JTextField txtSoTrang;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTenSPTimKiem;
    private javax.swing.JTextField txtTenTG;
    private javax.swing.JTextField txtTrangThai;
    // End of variables declaration//GEN-END:variables
}
