/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Lenovo
 */
public class StatisticalFrame extends javax.swing.JFrame {

    /**
     * Creates new form StatisticalFrame
     */
    public StatisticalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelThongKe1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        labelThongKe1 = new javax.swing.JLabel();
        btnIn1 = new javax.swing.JButton();
        labelNgayBatDau1 = new javax.swing.JLabel();
        dateNgayBatDau1 = new com.toedter.calendar.JDateChooser();
        labelNgayKetThuc1 = new javax.swing.JLabel();
        dateNgayKetThuc1 = new com.toedter.calendar.JDateChooser();
        btnThoat1 = new javax.swing.JButton();
        btnThongKe1 = new javax.swing.JButton();
        btnTim1 = new javax.swing.JButton();
        cbLoaiThongKe1 = new javax.swing.JComboBox<>();
        labelLoaiThongKe1 = new javax.swing.JLabel();
        labelTongDoanhThu = new javax.swing.JLabel();
        labelValueDoanhThu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThongKe = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelThongKe1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        labelThongKe1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelThongKe1.setText("THỐNG KÊ DOANH THU");

        btnIn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer.png"))); // NOI18N
        btnIn1.setText("In thống kê");

        labelNgayBatDau1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNgayBatDau1.setText("Thống kê từ ngày");

        dateNgayBatDau1.setDateFormatString("yyyy-MM-dd");

        labelNgayKetThuc1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNgayKetThuc1.setText("Đến ngày");

        dateNgayKetThuc1.setDateFormatString("yyyy-MM-dd");

        btnThoat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/out.png"))); // NOI18N
        btnThoat1.setText("Thoát");
        btnThoat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoat1ActionPerformed(evt);
            }
        });

        btnThongKe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/analytics-1.png"))); // NOI18N
        btnThongKe1.setText("Thống kê");
        btnThongKe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKe1ActionPerformed(evt);
            }
        });

        btnTim1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btnTim1.setText("Tìm");
        btnTim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim1ActionPerformed(evt);
            }
        });

        cbLoaiThongKe1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbLoaiThongKe1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thống kê trong ngày", "Thống kê trong tháng", "Thống kê trong năm", "Tùy chọn" }));

        labelLoaiThongKe1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelLoaiThongKe1.setText("Chọn loại thống kê:");

        javax.swing.GroupLayout panelThongKe1Layout = new javax.swing.GroupLayout(panelThongKe1);
        panelThongKe1.setLayout(panelThongKe1Layout);
        panelThongKe1Layout.setHorizontalGroup(
            panelThongKe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(panelThongKe1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnThoat1)
                .addGap(289, 289, 289)
                .addComponent(labelThongKe1)
                .addContainerGap(397, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThongKe1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelThongKe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLoaiThongKe1)
                    .addComponent(labelNgayBatDau1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelThongKe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThongKe1Layout.createSequentialGroup()
                        .addComponent(dateNgayBatDau1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(labelNgayKetThuc1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateNgayKetThuc1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelThongKe1Layout.createSequentialGroup()
                        .addComponent(cbLoaiThongKe1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(383, 383, 383)
                        .addComponent(btnTim1)
                        .addGap(25, 25, 25)
                        .addComponent(btnThongKe1)
                        .addGap(45, 45, 45)
                        .addComponent(btnIn1)))
                .addContainerGap())
        );
        panelThongKe1Layout.setVerticalGroup(
            panelThongKe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThongKe1Layout.createSequentialGroup()
                .addGroup(panelThongKe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelThongKe1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelThongKe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNgayKetThuc1)
                            .addComponent(dateNgayKetThuc1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelThongKe1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panelThongKe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelThongKe1)
                            .addComponent(btnThoat1))
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelThongKe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelThongKe1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(panelThongKe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnIn1)
                                    .addComponent(btnThongKe1)
                                    .addComponent(btnTim1)))
                            .addGroup(panelThongKe1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(panelThongKe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbLoaiThongKe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelLoaiThongKe1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(panelThongKe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNgayBatDau1)
                            .addComponent(dateNgayBatDau1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38))
        );

        labelTongDoanhThu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTongDoanhThu.setText("Tổng doanh thu:");

        labelValueDoanhThu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelValueDoanhThu.setText("valueDoanhThu");

        tableThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa đơn", "Tên nhân viên", "Tên khách hàng", "Số điện thoại", "Địa chỉ", "Email", "Ngày lập hóa đơn", "Tổng tiền hóa đơn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableThongKe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelThongKe1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelTongDoanhThu)
                        .addGap(28, 28, 28)
                        .addComponent(labelValueDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelThongKe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTongDoanhThu)
                    .addComponent(labelValueDoanhThu))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoat1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new HomeFrame().setVisible(true);
    }//GEN-LAST:event_btnThoat1ActionPerformed

    private void btnThongKe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKe1ActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_btnThongKe1ActionPerformed

    private void btnTim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTim1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnTim1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatisticalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnIn1;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThoat1;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnThongKe1;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnTim1;
    private javax.swing.JComboBox<String> cbLoaiThongKe;
    private javax.swing.JComboBox<String> cbLoaiThongKe1;
    private com.toedter.calendar.JDateChooser dateNgayBatDau;
    private com.toedter.calendar.JDateChooser dateNgayBatDau1;
    private com.toedter.calendar.JDateChooser dateNgayKetThuc;
    private com.toedter.calendar.JDateChooser dateNgayKetThuc1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelLoaiThongKe;
    private javax.swing.JLabel labelLoaiThongKe1;
    private javax.swing.JLabel labelNgayBatDau;
    private javax.swing.JLabel labelNgayBatDau1;
    private javax.swing.JLabel labelNgayKetThuc;
    private javax.swing.JLabel labelNgayKetThuc1;
    private javax.swing.JLabel labelThongKe;
    private javax.swing.JLabel labelThongKe1;
    private javax.swing.JLabel labelTongDoanhThu;
    private javax.swing.JLabel labelValueDoanhThu;
    private javax.swing.JPanel panelThongKe;
    private javax.swing.JPanel panelThongKe1;
    private javax.swing.JTable tableThongKe;
    // End of variables declaration//GEN-END:variables
}
